function excepcionGenerica() {
    try {
        return a + b;
    } catch (error) {

        alert(error.message)
    }
}